### ISSUE TITLE
Custom CSS, won't work 

### ISSUE THREAD

**Issue by Skyfay** [timvisee/send#106]
Hey, I tried to make a custom css. However, somehow this is not accepted.
I tried using a public url and in the container under "custom_assets" but it doesn't work.
`- UI_CUSTOM_CSS=custom_assets/custom.css`
`- UI_CUSTOM_CSS=https://example.com/custom.css`
Can you possibly help me further?

**Comment by wolfgangzwiauer** [comment]
Hey, I had exactly the same issue with docker.
This seems to be fixed in the latest docker snapshot - `registry.gitlab.com/timvisee/send:master-e030c46a` (not quite sure why this release is not tagged as `latest`)

**Comment by Skyfay** [comment]
Okay thank you very much.
I have another little problem. Maybe you can help me here too.
There used to be a picture in that area. I wanted this too and added it manually to the code and mounted it in the container as I always do. However, he somehow does not adopt the code. Maybe someone can tell me what I'm doing wrong.

**Comment by timvisee** [comment]
> This seems to be fixed in the latest docker snapshot - `registry.gitlab.com/timvisee/send:master-e030c46a` (not quite sure why this release is not tagged as `latest`)

I've just released `v3.4.21`. It should be available once this pipeline succeeds: https://gitlab.com/timvisee/send/-/pipelines/630739924

That will also retag the `master` image.
