### ISSUE TITLE
Deleting expirated files from storage

### ISSUE THREAD

**Issue by madalozzo** [timvisee/send#109]
Should application delete expired files or must I configure that outside? I'm using storage option but files still there after expiration.

**Comment by madalozzo** [comment]
I found an answer! https://github.com/timvisee/send/issues/59#issuecomment-985663654

**Comment by timvisee** [comment]
Correct, you'll have to configure this externally!

I should probably add a page some time to clearly state this, with instructions to do so.

Sorry for my late reply.

**Comment by boomam** [comment]
As the most recent version of this question (other being #59 ) -  
@timvisee based on what you said in #59, is it safe to assume that files written to the S3 bucket, the 'X-' at the beginning of the file names, is the expiration time in days?  
&nbsp;  
I ask, as if we are to create a lifecycle policy that doesnt blindly delete things, it would be good to have an understanding of the file naming convention, so we can apply some logic too it.

Thanks!

**Comment by timvisee** [comment]
> As the most recent version of this question (other being #59 ) -  
> @timvisee based on what you said in #59, is it safe to assume that files written to the S3 bucket, the 'X-' at the beginning of the file names, is the expiration time in days?  
> &nbsp;  
> I ask, as if we are to create a lifecycle policy that doesnt blindly delete things, it would be good to have an understanding of the file naming convention, so we can apply some logic too it.  

That is correct. The prefix is the number of days.

So you can delete a file like `3-abcdefg` 3 days after it's creation.
