### ISSUE TITLE
Unable to get base url

### ISSUE THREAD

**Issue by loulax** [timvisee/send#114]
I tried everything to to change 127.0.0.1 to domaine name but it doesn't work, i supply you to help me plz?
Is in the config.js BASE_URL: "ff.mozilla.org" =>  BASE_URL: "mydomain.com"
and set DETECT_BASE_URL: false => BASE_URL: true ??

**Comment by loulax** [comment]
Hi thanks, i tried this but doesn't work ... Is this normal when i install send, the parameter DETECT_BASE_URL is true by default?

**Comment by loulax** [comment]
My send is behing an nginx reverse proxy, is probably for that no?

**Comment by timvisee** [comment]
No, `DETECT_BASE_URL` is `false` by default, as you can see here:

https://github.com/timvisee/send/blob/9e188bc76c42b8458985c56441d5757d7a62294f/server/config.js#L181-L185

Are you sure these environment variables are configured at the correct location, and that Send is able to pick them up?

If you are Docker (and docker-compose), take a look at this example: https://github.com/timvisee/send-docker-compose/blob/master/docker-compose.yaml

View more here: https://github.com/timvisee/send-docker-compose

**Comment by loulax** [comment]
Yeah it works now, it was correct in the config.js but DETECT BASE_URL in package.json was setted to true so i changed to false and now the link is generated with my domain name!
Thank you for the support !

**Comment by timvisee** [comment]
Good to see it worked! Happy to help.
