### ISSUE TITLE
How to solve the puzzle of max filesize?

### ISSUE THREAD

**Issue by arkprocession** [timvisee/send#128]
i understand its in kb. no matter what i input even after i convert i get a wrong size.

i am trying to make send 100gb available. What should i write in max filesize?

**Comment by null-zero** [comment]
`107374182400`

107,374,182,400

**Comment by timvisee** [comment]
The value should be in bytes.

The value `107374182400` is correct, which is:

```
100 * 1024 * 1024 * 1024
      ^      ^      ^
      gb   * kb   * b
=
107374182400 bytes
```

The default value, of 2.5GB, can be seen here:
https://github.com/timvisee/send/blob/1d75366f66f431ff3669eadf8f530999cabd0560/server/config.js#L158
