### ISSUE TITLE
Option to save to and load from a savestate file

### ISSUE THREAD

**Issue by MarBaws** [timvisee/send#131]
I power off my server regularly, so I was wondering if there is some way to stop the running instance of Send and resume it after a reboot. Currently, I stop the instance and after a fresh start it forgets all download links created before (the uploaded files are of course still there). As a side effect, this also means quite a few orphan files, which I have to externally clean up, because Send is probably not aware of them after a restart. If doesn't yet exist, I believe that this would be best implemented with an environment variable that optionally points to a save file. I hope that it is possible in the project's current state, at the least.

I believe dumping the entire process with a tool such as criu would be impractial and unnecessary, and I have also not succeeded in doing it, probably because my instance is run through a systemd service running a bash script running "npm run prod".

Any answers are greatly appreciated. If there is some other way to retain the same state after a reboot, I am open to suggestions.

**Comment by timvisee** [comment]
Redis is used for this. Please make sure you are running a Redis instance and have it configured correctly.

If Send can't connect to Redis, its 'state' is lost on restart.

If you still experience issues, feel free to open this again.
