### ISSUE TITLE
Any plans to use rust for refactoring?

### ISSUE THREAD

**Issue by xczh** [timvisee/send#132]
Thank you for making some improvements on the original `Firefox Send` service, which makes it easier for many people to deploy their own instances :) 

I have been using the private instance of `Firefox Send`. I think its end-to-end encrypted file transfer design is very useful. As the maintenance of the firefox send service stops, some dependent and third-party software libraries are outdated, and some have security vulnerabilities. In addition, performance may also be an issue.

I want to ask if there is any plan to use the rust/go language to reconstruct the server? If so, I am willing to participate. thx :slightly_smiling_face:

**Comment by timvisee** [comment]
Thanks for your suggestion.

I love the Rust language (as you might have seen on my profile), but I have no plans to refactor bits of it with Rust.

I don't think such approach will be very beneficial, and it will probably make development and deployment harder (extra toolchains, multiple architectures) until the full project is rewritten. Nor do I think it will improve performance by much. The heavy work is done by libssl, and a server is likely limited by its available network bandwidth.

Please note that I do my best to fix vulnerabilities in dependencies as soon as discovered/registered.

**Comment by xczh** [comment]
All right. Thanks for your kindly reply :)
