### ISSUE TITLE
Serving uploads behind existing Reverse-Proxy

### ISSUE THREAD

**Issue by widestorm** [timvisee/send#14]
Disclaimer: Im running it in a docker container on my Synology NAS.

I'm running a reverse Proxy to serve https://send.example.org to my local docker container --> http://localhost:1443.

Now I'm unable to upload a file through https://send.example.org and when I'm using http://localhost:1443 to upload it works fine but serves a **https**://localhost:1443 download link.

Would it be possible to get this setup working?

I'm not an expert on any of this so excuse if I'm making an error here on my side and it is possible already.

**Comment by timvisee** [comment]
Uploads are done through a websocket. There might be an configuration issue regarding this in your reverse proxy.

Are you using nginx? You might find this template useful: https://github.com/timvisee/send-docker-compose

**Comment by widestorm** [comment]
Wow thanks a lot for the incredibly quick response. The websocket hint helped immensely.
The solution was simply adding custom headers in the reverse proxy rules:

Name: “Upgrade”, Value: “$http_upgrade”
Name: “Connection”, Value: “$connection_upgrade”

**Comment by timvisee** [comment]
Fantastic! Happy to see it works. Thanks for sharing your solution.
