### ISSUE TITLE
File selection do not work and Firefox / Android 11

### ISSUE THREAD

**Issue by mh4ckt3mh4ckt1c4s** [timvisee/send#142]
When I try to upload a file from Firefox on my Android 11 phone, I am prompted to the file selection but once the file selected, it doesn't appear on the website (still on the same "select files to send" window). I tried both on my instance and on the https://send.vis.ee  instance without success. 

I tried with my Chromium-based DuckDuckGo browser on the same device without problem. I have a bunch of add-ons on Firefox such as adblockers or privacy-related tools that tend to break websites, but I investigated each of them and tried to disable them without success.

**Comment by timvisee** [comment]
That's weird! Thanks for your report.

I haven't seen this before and am not experiencing this myself on Firefox Nightly on Android 13.

Do you happen to know if you have similar issues on other (non Send) wrbsites? Could this somehow be related to a permissions problem?

**Comment by mh4ckt3mh4ckt1c4s** [comment]
So after more investigation a feature in my phone vendor add-ons (MIUI 12 optimisation) was triggering the bug in Firefox... (no idea how or why). It's working now. Thanks for the help !

**Comment by timvisee** [comment]
Great to see you got it to work!
