### ISSUE TITLE
Use Cloudflare Zero Trust Tunnels / Access to restrict uploading

### ISSUE THREAD

**Issue by andresindlp** [timvisee/send#143]
I've been trying for some time now to lock down the upload page using Cloudflare's Access and Tunnels but I can't get it to work.

How it should work:

- Only authenticated users can enter the main page: https://yourdomain.com/send (ideally send.yourdomain.com but that would be more difficult as Cloudflare doesn't allow to target only that specific path, as stated in [their docs](https://developers.cloudflare.com/cloudflare-one/policies/access/app-paths/))
- Everyone should be able to access https://yourdomain.com/send/download/xxxxxxxxxxxxxxxxxx.

I'm thinking an easier solution would be able to have optional separate paths such as `/upload` and `/download`, this way `/upload` could easily be managed.

This is the best I've been able to come up with:
![1](https://user-images.githubusercontent.com/35582438/214145410-c706ab46-523a-45c1-b98a-6c9ff54c0a06.png)
![2](https://user-images.githubusercontent.com/35582438/214145422-37fde97c-6c26-43cb-afe4-6fb653978f43.png)
![3](https://user-images.githubusercontent.com/35582438/214145435-2efa66b3-f073-4039-9584-98029787658c.png)
End result:
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/35582438/214145805-03dc5b9b-cbf4-40e5-b3c3-521815aac263.png">

If someone knows how to please let me know :)

**Comment by HeyMika** [comment]
For me it looks like something is wrong with your Send docker instance. I just entered a subdomain in Cloudflare tunnels and local IP address and it worked instantly.

**Comment by andresindlp** [comment]
> For me it looks like something is wrong with your Send docker instance. I just entered a subdomain in Cloudflare tunnels and local IP address and it worked instantly.

It indeed works perfectly fine. It however does not when you want to lock down access to the upload page.

I ended up going with [picoshare](https://github.com/mtlynch/picoshare), it's not perfect but it does almost everything I need it to, including restricted access to the upload page. Can't use it with Cloudflare Tunnels though, when trying to upload large files it just doesn't work so I'm using SWAG from linuxserver.io, it's not perfect but it gets the job done.

**Comment by HeyMika** [comment]
Ah okay, but nice that you found a solution :)

**Comment by nickthegreek** [comment]
I have blocked access to `/api/ws` so that only authenticated users can upload. But everyone can download.

**Comment by Skyfay** [comment]
Isn't that against Cloudflare's TOS? 

_2.8 Limitation on Serving Non-HTML Content
The Service is offered primarily as a platform to cache and serve web pages and websites. Unless explicitly included as a part of a Paid Service purchased by you, you agree to use the Service solely for the purpose of serving web pages as viewed through a web browser or other functionally equivalent applications and rendering Hypertext Markup Language (HTML) or other functional equivalents. Use of the Service for serving video (unless purchased separately as a Paid Service) or a disproportionate percentage of pictures, audio files, or other non-HTML content, is prohibited._

Uploading and downloading the files then also goes via Cloudflare. I think this violates the TOS.

**Comment by ankitsinghaniyaz** [comment]
@nickthegreek blocking `/api/ws` did the trick. Though how are you authenticating yourself as now no page will throw any error.
