### ISSUE TITLE
Thunderbird FileLink extension

### ISSUE THREAD

**Issue by tdulcet** [timvisee/send#15]
There were several issues requesting this feature: https://github.com/mozilla/send/issues/847, https://github.com/mozilla/send/issues/496 and https://github.com/mozilla/send/issues/1353 and also BMO [bug 1516252](https://bugzilla.mozilla.org/show_bug.cgi?id=1516252).

I have wanted this feature for years and since no one else has implemented it yet\*, I decided to create a Thunderbird add-on/extension myself. It allows users to enter the URL of the Send instance they want to use, along with other info. It will then encrypt and upload the files to that Send server. It requires at least Thunderbird 78\*\* and should support all v3 Send service instances. See [my repository](https://github.com/tdulcet/Thunderbird-Send) for more info. Here is an example of what the account management pages looks like:
 
![image](https://user-images.githubusercontent.com/15305150/113866162-d40a5180-9761-11eb-8bdd-cb4e7998668f.png)

I wanted to get permission to use [the icon](https://github.com/timvisee/send/blob/master/assets/icon.svg) from this repository for the add-on. My repository is also MPL-2.0 licensed, so I believe there should not be any issues, but I wanted to check anyway, as I saw you had issues using the Firefox Send logo in this repository.

I also wanted to thank you for continuing to maintain this after Mozilla discontinued it! 🙏

At some point, I may submit the add-on to Addons.thunderbird.net (ATN), although I am currently still testing it. Feedback is welcome! If anyone wants to try it in the meantime, you can download it with this command:
```sh
git clone --recurse-submodules https://github.com/tdulcet/Thunderbird-Send.git
```
Then follow [these instructions](https://developer.thunderbird.net/add-ons/mailextensions/hello-world-add-on#installing) to install it in Thunderbird.

\* Someone attempted to create a TB add-on [here](https://github.com/hellosct1/firefox-send/tree/master/src-thunderbird), but it uses the `/share` endpoint and thus does not actually encrypt the files before uploading them, which of course defeats the primary purpose of this service. It also is hardcoded to the discontinued Firefox Send service.
\*\* The options page does not currently work in TB 78 because of [bug 1641577](https://bugzilla.mozilla.org/show_bug.cgi?id=1641577), although the account management pages work fine. It only has a single minor option, which is not necessary to use the add-on. The bug was fixed in TB 86 Beta and should be included in TB 91.

**Comment by timvisee** [comment]
Very nice work! I've wanted to see this as well, great to see you've implemented it.

> I wanted to get permission to use [the icon](https://github.com/timvisee/send/blob/master/assets/icon.svg) from this repository for the add-on. My repository is also MPL-2.0 licensed, so I believe there should not be any issues, but I wanted to check anyway, as I saw you had issues using the Firefox Send logo in this repository.

Yeah, feel free to use it! The original (Firefox) logo caused trouble because it used Firefox' branding. I've made the current icon myself, so it won't be an issue.

I'll definitely give the extension a try. It seems that you've implemented all cryptography within the extension, which I'm quite surprised with as it's somewhat tricky.

Releasing it as extension would be awesome. The only thing I'd be worried about is using my host as default if it is ever integrated within Thunderbird by default, due to the amount of traffic it might generate. Though, releasing it as separate extension should be fine, so feel free to keep it this way. If it ever becomes a problem, I'll be sure to reach out to you.

> I also wanted to thank you for continuing to maintain this after it was discontinued by Mozilla! 🙏

No problem! Loved the service, so I wanted to keep it alive.

**Comment by tdulcet** [comment]
> Yeah, feel free to use it!

Thanks! I think it is good to have consistency between the icon on the Send website and the add-on.

> I'll definitely give the extension a try. It seems that you've implemented all cryptography within the extension, which I'm quite surprised with as it's somewhat tricky.

Yes, I adapted most of the encryption code from this and Mozilla's upstream repository. It mainly required removing the NodeJS dependencies, removing support for old browsers and simplifying the code by using more modern ES7+ JS syntax. Your `ffsend` and `ffsend-api` repositories were also very helpful while I was creating the add-on, as there is no documentation on the Send API, I was able to use those to determine the correct design patterns for the add-on. For example, `ffsend` checks the Send server version using the `/__version__` endpoint before uploading files, which I was able to include in the add-on.

> The only thing I'd be worried about is using my host as default if it is ever integrated within Thunderbird by default, due to the amount of traffic it might generate.

OK, I doubt they would ever use your host by default without first asking for your permission. Note that the bug I referenced above was marked as WONTFIX after Firefox Send was discontinued last year. I requested they reopen it about a week ago, but I have gotten no response, so unfortunately it does not look like they will integrate the functionality into Thunderbird, at least not anytime soon...

> Edit: just gave it a try, and it seems to work very well. I'm running Thunderbird 78.7.1 (64-bit). Well done!

Thanks for trying it out! I am glad it worked well for you.

**Comment by timvisee** [comment]
> `ffsend` checks the Send server version using the `/__version__` endpoint before uploading files, which I was able to include in the add-on.

Speaking of which, I thought a 'Verify' button behind the host field could be useful. Which checks whether `/__version__` is valid after entering a host.

**Comment by tdulcet** [comment]
> Speaking of which, I thought a 'Verify' button behind the host field could be useful. Which checks whether `/__version__` is valid after entering a host.

Great idea! Thanks for the feedback. I just added it in https://github.com/tdulcet/Thunderbird-Send/commit/d2593719546f45a33bacd45780cff19af51d0452. It will display a message at the top of the account management page after clicking the "Verify" button.

**Comment by tdulcet** [comment]
I published the add-on to ATN: https://addons.thunderbird.net/en-US/thunderbird/addon/filelink-provider-for-send/. It requires [Thunderbird 91](https://www.thunderbird.net/en-US/thunderbird/91.0/releasenotes/), which was released earlier this month. Feedback is welcome.

I also recently added a popup to extension so users can specify the download and time limits for each file before it is uploaded.

@timvisee - If you would like to close this issue, could it please be added on the [Clients section](https://github.com/timvisee/send#clients) of your README?

**Comment by timvisee** [comment]
Fantastic! Great work.

> If you would like to close this issue, could it please be added on the Clients section of your README?

Sure. I can't easily add this right now. Feel free to submit a PR for this in the mean time.

**Comment by tdulcet** [comment]
There have been a [couple enhancements](https://webextension-api.thunderbird.net/en/latest/changes/beta96.html) to the FileLink/CloudFile API in TB 91.4.1, which may necessitate some changes to the Send server API in order for my add-on to use them. I was not sure if I should create new issues or reuse this one.

* TB now allows users to rename files after they have been uploaded. This does not seem to be currently supported by the Send API. I propose updating the `/api/params/` endpoint to also accept a new filename, as it currently only supports changing the download limit. This could presumably also be used by `ffsend` and other Send clients.
* Extensions can now provide a URL for the icon of the service after uploading a file, which is added to the message instead of using the extension's icon. Some of the Send service instances of course use different icons and this would allow the correct one to be added to the message. However, there does not currently seem to be a consistent path for the icon. Of the 17 [public Send instances](https://github.com/timvisee/send-instances/), 12 use `/icon.26e159f8.svg`, one uses `/icon.fd04d81a.svg`, one uses `/portailpro-logo.bff132c0.png`, one uses `/logo.9be52fed.png`, one uses `/logo_acted_full.1d533b41.svg` and one is down. I propose something like a new `/__icon__` endpoint which returns the icon, either directly or by an [HTTP 301](https://en.wikipedia.org/wiki/HTTP_301) redirect. An alternative would be to include a `favicon.svg` file, which is already a standard supported by many browsers (see [here](https://caniuse.com/link-icon-svg)), but some Send instances may not want to use an SVG icon.

Of course, neither of these feature requests are a priority, but I thought I would mention them in case someone was interested in implementing either.

@timvisee - While investigating this, I also noticed that Send still uses the Firefox Send [favicon](https://send.vis.ee/favicon.ico) ([source](https://github.com/timvisee/send/blob/master/public/favicon.ico)):
![image](https://user-images.githubusercontent.com/15305150/146769027-b0c2f0d5-8c59-4117-bf3f-3c5b588a4233.png)
