### ISSUE TITLE
Icon Licensing

### ISSUE THREAD

**Issue by HappiePlant** [timvisee/send#154]
I made a little Powershell script for including ffsend in the Windows Explorer "Send to" menu which I want to publish on GitHub. I want to include the [icon](https://github.com/timvisee/send/blob/master/assets/icon-64x64.png) in the repo converted to .ico format. How can give legal attribution for the icon in the repo?

**Comment by timvisee** [comment]
No legal attribution for the icon required.

Thank you for asking this.

**Comment by HappiePlant** [comment]
Thank you!
