### ISSUE TITLE
Nginx Proxy won't upload files

### ISSUE THREAD

**Issue by xbdmHQ** [timvisee/send#156]
Hi,

i setup my own send instance, but when i go and test it won't upload. i think i may of done something wrong but i done everything correctly

**Comment by Chiogros** [comment]
Hi,

Try to use these headers in your server's `/` location.
```
server {
        [...]

        location / {
                proxy_pass http://<your-send-instance-IP>;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr; 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_pass_header Authorization;
        }
}
```

Hope it helps.

**Comment by xbdmHQ** [comment]
Ok, I will try it out

**Comment by xbdmHQ** [comment]
> proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection "upgrade";
>                 proxy_set_header Host $host;
>                 proxy_set_header X-Real-IP $remote_addr; 
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header Host $http_host;
>                 proxy_pass_header Authorization;
>         }
> }

Ok, thanks for that config, and also found the issue it was the Redis. I had to remove it and it worked!
