### ISSUE TITLE
If you click the logo then you're redirected to the homepage. How can I turn this off?

### ISSUE THREAD

**Issue by anon243** [timvisee/send#176]

**Comment by timvisee** [comment]
No, this behavior cannot be changed without modifying code.

This is very common practice though. Many users expect to be directed to the home page when clicking the main logo.

**Comment by anon243** [comment]
Yeah, the issue is the following:

I run Send where the upload functionality is behind Authentik. The download feature is however open to whoever got the link. When you refresh the page then the login screen is triggered which is normal behaviour, but if you click on the logo on the webpage then it's redirecting to the upload feature, which is bypassing Authentik somehow.
