### ISSUE TITLE
Using send with password behind apache reverse proxy failed

### ISSUE THREAD

**Issue by ralfi** [timvisee/send#182]
Hi,

first of all thanks a lot for send. 

I am try to setup my own instance behind apache reverse proxy followed by a docker setup.
Everything works well but if a set i upload file with password protection for download with the -really correct- password it fails.

Look at the browser console tells me the error 

  `http/1.1 401 Unauthorized` 

to my URL 

  `https://[my-base-URL]/api/metadata/[tag]`

The docker container send console tells me

  `[ 'https://[my-base-URL]', 'wss:[my-base-URL]' ]`

but no other messages.

My apache reverse proxy config is here:

```
    RewriteEngine on
    RequestHeader set X-Forwarded-Proto https

    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .* - [L]

    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*) ws://192.168.178.21:1234/$1 [P,L]

    ProxyPass "/" "http://192.168.178.21:1234/"
    ProxyPassReverse "/" "http://192.168.178.21:1234/"

```
My .env contains:
```

HOST=FQDN
SEND_BASE_URL=https://FQDN

```
Everything works as expected with `https://send.vis.ee` including password
What could be wrong that the password could not be recognized?

Regards!

**Comment by ralfi** [comment]
Hi there,
no hints for me?

**Comment by ralfi** [comment]
Yeah, it works!
Disabling additional basic authentication in my apache.conf and everything as expected.

**Comment by Mushoz** [comment]
I have the same issue, but with Nginx instead. Setting `proxy_set_header Authorization $http_authorization;` did not solve the issue for me. Any idea what I should try next?
