### ISSUE TITLE
Possible to move/copy over all issues from the old project?

### ISSUE THREAD

**Issue by rgpublic** [timvisee/send#3]
Thank you for continuing to work on this. Absolutely great software - it would really be a shame if it were abandoned. I wonder whether all the old issues shouldn't be moved over here or sth. Don't know whether this is possible in GitHub.

**Comment by danshilm** [comment]
I have recently come across a repo where issues were moved by a bot from its original repository, however, I cannot find that repo right now. Will edit if/when I do.

**Comment by timvisee** [comment]
Mozilla's issue [list](https://github.com/mozilla/send/issues) seems to contain a lot of issues that don't relate to this fork (or the public instance I'm running). I'm therefore don't think that importing all issues would be a good idea.
