### ISSUE TITLE
Are IP addresses still logged for 90 days?

### ISSUE THREAD

**Issue by lrq3000** [timvisee/send#38]
In the defunct Firefox Send, IP addresses were logged for 90 days.

Is this hardcoded somewhere in the software?

**Comment by timvisee** [comment]
@lrq3000 it is not. Send itself does not log IPs.

However, a reverse proxy you put in front of it may log IPs.

The configuration template at https://github.com/timvisee/send-docker-compose does log IPs as part of an access log by default.

The public instance I'm hosting at https://send.vis.ee/ follows this template, and therefore logs IPs.

**Comment by timvisee** [comment]
I suppose this is answered now. Closing the issue.

Feel free to open it again if you have any further questions.

**Comment by lrq3000** [comment]
Yes, thank you very much for the detailed clarification. Have a nice day!
