### ISSUE TITLE
clarification on "This browser might not be able to decrypt a file this big"

### ISSUE THREAD

**Issue by grrrrr** [timvisee/send#41]
I recently had  shared with me a number of files that totaled approx 2.2GB.

When I go to the link to download it displays a warning `This browser might not be able to decrypt a file this big` and gives 3 options

* Copy he link to open in another browser
* Try our favorite browser
* Continue with this browser

Selecting `Try our favorite browser`  gives you the option to `Download Firefox`.

The confusion I have is I am already using Firefox.  Is this expected behavior or is the "recommended" browser now something else?

Using:
* Debian 10
* 78.10.0esr (64-bit)

**Comment by timvisee** [comment]
If I recall correctly: older browsers have to download the full encrypted blob before decryption can take place. The larger the file, the more memory is consumed. This is why downloading large files on machines with limited resources could be a problem. The threshold for the warning you got is at 2GB and up.

I believe Firefox 78 is considered 'old', as the latest stable version is currently Firefox 89. But yeah, the way the message is presented it might seem a little weird.

Please note that I'm not 100% sure about these details. I'm writing this from memory.

> The confusion I have is I am already using Firefox. Is this expected behavior or is the "recommended" browser now something else?

So yeah, the recommended browser is still Firefox, but a later version. Remember that if your machine has sufficient resources, clicking through the warning should be perfectly fine.

**Comment by grrrrr** [comment]
Thanks for the clarificatin
