### ISSUE TITLE
Missing Nginx configuration: proposal

### ISSUE THREAD

**Issue by OrnithOrtion** [timvisee/send#44]
I didn't found any nginx configuration in this repo.

I did get stuck with websocket, but I have found this working:
[https://doku.s1gm4.eu/doku.php?id=wiki:services:drop](https://doku.s1gm4.eu/doku.php?id=wiki:services:drop)

**Comment by timvisee** [comment]
You might find this template useful: https://github.com/timvisee/send-docker-compose

It is not a direct Nginx template, but it uses Nginx as reverse proxy.

**Comment by OrnithOrtion** [comment]
Yes, thanks, but I didn't used docker.

**Comment by acourter27** [comment]
I'm running the docker container with my own nginx instance separately.

I have nginx set to route my domain to localhost:8006, and I'm running docker with this command:

sudo docker run -v $PWD/uploads:/uploads -p 8006:1443 \
    -e 'DETECT_BASE_URL=true' \
    -e 'REDIS_HOST=localhost' \
    -e 'BASE_URL=https://[domain]' \             << (it uses my actual domain here)
    registry.gitlab.com/timvisee/send:latest

The site is coming up without issue, but I can't upload. If I navigate to localhost:8006 I can upload a file without issue. Then, if I take that link, and replace localhost with my domain, I can download without issue.

When looking at the network web inspector, it gets to 'ws' and stops - the WebSocket Connection is Established but then immediately closed.

I believe it's something in my nginx configuration, but I can't figure it out. (As with above, the [domain] section actually has my domain info in it on my server.)

server {
        server_name [domain];
        location / {
                proxy_pass "http://localhost:8006";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/[domain]/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/[domain]/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = [domain]) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        server_name [domain];
    return 404; # managed by Certbot


}

**Comment by ekimber** [comment]
You are missing the HTTP upgrade config.
Look here:
https://www.serverlab.ca/tutorials/linux/web-servers-linux/how-to-configure-nginx-for-websockets/
or in the link posted in the first comment

**Comment by acourter27** [comment]
Thanks! I tried using the link he had above but I must have missed something.

When I added these two lines it started working:
proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

**Comment by ucyo** [comment]
For future reference: The error in our setup was, that `send` is running in user space (`uid:gid 1000:1000`) and the folder mounted via docker did not have the correct access rights. Be sure to check that the `uid:gid` are valid.
