### ISSUE TITLE
File location

### ISSUE THREAD

**Issue by gizamichal** [timvisee/send#47]
Hi, can you indicate the path where the uploaded files are located?

**Comment by timvisee** [comment]
Send stores files in a random temporary directory by default.

You can set the upload location with the `FILE_DIR` [variable](https://github.com/timvisee/send/blob/master/server/config.js#L173-L176).

Here's an example:
https://github.com/timvisee/send-docker-compose/blob/6f517849cd6ef0a784bd02265346baade612d7f9/docker-compose.yaml#L51-L52

Hope this helps! Feel free to open this again if you have any further questions.
