### ISSUE TITLE
How to connect to Redis from send docker container?

### ISSUE THREAD

**Issue by tjoanp** [timvisee/send#58]
First things first: I'm new to docker.

I've been sitting for some time trying to get send working in docker. I started with installing redis-server on the Ubuntu docker host, assuming REDIR_HOST=localhost would work, but links expired when send container restarted. And since "docker logs sendcontainer" responds with absolute nothing I'm working completely in the dark. I however had a theory; redis-server listens on 127.0.0.1 on the host, and thereby doesn't accept connections from containers.

So I followed the instructions on https://github.com/timvisee/send/blob/master/docs/docker.md Examples (Run totally self-hosted...) and created a docker network, started a redis container (it's not called redis-server by the way). But the send run example doesn't specify where the redis host is, and my links still expired when restarting send container.

Before giving up I though i could test specifying REDIS_HOST=172.19.0.2 (the redis container ip address), and behold, the links doesn't expire when restarting send! But I feel this 172 address could change any time?

Question 1: How is containerized send supposed to connect to redis when a) redis is running on the host, and b) running in a container on the same docker network?

Question 2: If redis is a requirement, why isn't it included in the docker image?

Best regards,
Andreas

**Comment by timvisee** [comment]
> I've been sitting for some time trying to get send working in docker. I started with installing redis-server on the Ubuntu docker host, assuming REDIR_HOST=localhost would work, but links expired when send container restarted. And since "docker logs sendcontainer" responds with absolute nothing I'm working completely in the dark. I however had a theory; redis-server listens on 127.0.0.1 on the host, and thereby doesn't accept connections from containers.
> 
> So I followed the instructions on https://github.com/timvisee/send/blob/master/docs/docker.md Examples (Run totally self-hosted...) and created a docker network, started a redis container (it's not called redis-server by the way). But the send run example doesn't specify where the redis host is, and my links still expired when restarting send container.
> 
> Before giving up I though i could test specifying REDIS_HOST=172.19.0.2 (the redis container ip address), and behold, the links doesn't expire when restarting send! But I feel this 172 address could change any time?

This sounds like a Redis connection issue, yes. If you'd like to set this up yourself, I recommend to use the 'default' Redis container provided via Docker. Containers are immutable by default, meaning some extra configuration is required to ensure no data is lost when the container stops.

Note that the page you linked purely lists how to start a Send container, and doesn't explain how to set up Redis. Redis is not a requirement when running in development mode.

> Question 1: How is containerized send supposed to connect to redis when a) redis is running on the host, and b) running in a container on the same docker network?

If the two services are running within the same Docker network, they should be able to connect. If Redis is running on your host, and Send is running in the container, you may expose Redis to the container or choose to use the host network all together within Send as well.

> Question 2: If redis is a requirement, why isn't it included in the docker image?

This is common Docker practice, to run each service in it's own container. This makes the whole thing modular, better allowing updates, different configurations and proper handling of crashes.

---

Docker can be somewhat confusing when setting things up manually.

I therefore highly recommend to look into the [`send-docker-compose`](https://github.com/timvisee/send-docker-compose) example I've set up instead. Through Docker compose, it sets up the Send stack with all requirements for you.

Sorry for my late message. I somehow missed this.

**Comment by timvisee** [comment]
Closing this. Feel free to open it again if further issues arise.
