### ISSUE TITLE
Docker: Files not cleaned up automatically

### ISSUE THREAD

**Issue by xnaas** [timvisee/send#59]
I've noticed that files do not clean themselves up from the mounted filesystem automatically after they expire. The files will only be deleted if you manually click the `X` in the Send web GUI.

* [relevant docker-compose.yml](https://github.com/xnaas/docker-compose.yml/blob/112d9d8930be65abbd40e7abd2cb64f1ed965704/docker-compose.yml#L482-L518)
* [common.env](https://github.com/xnaas/docker-compose.yml/blob/master/envs/common.env)
* [send.env](https://gist.github.com/xnaas/140f2ff8148fa6157c4b40b7e29b6cc4)

If there's something wrong with my config, please let me know.

**Comment by timvisee** [comment]
That is correct! Send itself does not clean up files that expire (time), it does clean up files that reached their download limit or that an uploader deletes explicitly. I believe this is because it would require a background task within Send, which is somewhat nasty.

Instead, when using S3, a 'Lifecycle Configuration' can be configured so S3 automatically cleans up expired files for you. This is also how Mozilla originally implemented this.

Since you seem to be storing files on disk, rather than in S3, you'll have to set up a job to automatically clean up old files.

All uploads are prefixed with a number, which specifies the expiry time of a file in number of days. For example, the file `7-abcdef` should expire 7 days after its creation time.

You can find an example cronjob to remove old files here: https://github.com/timvisee/send-docker-compose/blob/master/gc.cron

**Comment by xnaas** [comment]
Ah, I see. Makes sense if they were leveraging S3 stuff originally.

Thanks for the clarification!

**Comment by timvisee** [comment]
No problem! Maybe I should clarify this somewhere in the set-up documentation.

**Comment by koehn** [comment]
FWIW, an easy unix way to purge expired files would be to periodically run this from your storage directory:

```bash
for i in $(ls | awk -F '-' '{print $1}' | sort | uniq) ; do 
  find . -mtime +"$i" -name "$i-*" -delete
done
```

This assumes that the filenames are `<days before expiry>-<file identifier>` e.g., `30-5041c2903273ce9e` would expire in thirty days.

**Comment by erbelion** [comment]
i fixed this problem by adding a new cleanup container to my compose file:

```
  cleanup:
    image: alpine:latest
    restart: always
    environment:
      - MAX_EXPIRE_SECONDS=259200   # 3 days
      - CLEANUP_INTERVAL_SECONDS=86400   # 24 hours
    volumes:
      - /mnt/storagebox/send:/uploads
    command:
      - /bin/sh
      - -c
      - |
        while true; do
          MAX_EXPIRE=$${MAX_EXPIRE_SECONDS:-259200}
          CLEANUP_INTERVAL=$${CLEANUP_INTERVAL_SECONDS:-86400}
          echo "[Cleaner] Starting cleanup..."
          echo "[Cleaner] Deleting files older than $$MAX_EXPIRE seconds"
          find /uploads -type f -mmin +$$((MAX_EXPIRE / 60)) -print -delete
          echo "[Cleaner] Cleanup done. Sleeping $${CLEANUP_INTERVAL}s..."
          sleep $$CLEANUP_INTERVAL
        done
```

**Comment by infocillasas** [comment]
Thanks a lot, it helped me setting up cleaning on my send instance

> i fixed this problem by adding a new cleanup container to my compose file:
> 
> ```
>   cleanup:
>     image: alpine:latest
>     restart: always
>     environment:
>       - MAX_EXPIRE_SECONDS=259200   # 3 days
>       - CLEANUP_INTERVAL_SECONDS=86400   # 24 hours
>     volumes:
>       - /mnt/storagebox/send:/uploads
>     command:
>       - /bin/sh
>       - -c
>       - |
>         while true; do
>           MAX_EXPIRE=$${MAX_EXPIRE_SECONDS:-259200}
>           CLEANUP_INTERVAL=$${CLEANUP_INTERVAL_SECONDS:-86400}
>           echo "[Cleaner] Starting cleanup..."
>           echo "[Cleaner] Deleting files older than $$MAX_EXPIRE seconds"
>           find /uploads -type f -mmin +$$((MAX_EXPIRE / 60)) -print -delete
>           echo "[Cleaner] Cleanup done. Sleeping $${CLEANUP_INTERVAL}s..."
>           sleep $$CLEANUP_INTERVAL
>         done
> ```

**Comment by Govthub** [comment]
All you need to do is to deposit 200 to this address. bitcoin address below
and it will be pulled.All you need to do is to deposit  200$ bitcoin to
this address. bitcoin address below and it will be pulled immediatelyand
rectify. ..bc1q9947hg38qca6zxmjw5ca6p9w922tz4vprxx3pq.  To make it
recognize and clear errors To make it recognize and clear errors
