### ISSUE TITLE
bandwidth control

### ISSUE THREAD

**Issue by mqu** [timvisee/send#7]
hello all.
I would be pleased to have an option (env variable) to limit upload and download bandwidth avoiding saturation on global network link.

best regards, Marc.

**Comment by timvisee** [comment]
Could you enforce a bandwidth limit with a reverse-proxy in front of it instead, with Nginx for example? That would probably work the best, and won't require code changes in Send.

As far as I know, Nginx supports setting both a connection rate and bandwidth limit.

**Comment by mqu** [comment]
Oh yes ; did not think about that ! thank you so much.

**Comment by timvisee** [comment]
No problem! Closing this now.

Let me know if you need any help. Feel free to open this again.
