### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by leucos** [timvisee/send#77]
First, thanks for maintaining this fork. It is really a great tool and it is really nice to see it thriving.

I wonder if there are any documentations regarding the Send API. I glanced quickly in `ffsend` and `ffsend-api` projects too and didn't find anything.

Since some client implementations have been written (e.g. TB FileSend), I guess it must exist somewhere (unless they reverse-engineered it).

Any pointers ?

Thanks a lot

**Comment by timvisee** [comment]
There currently is not, as it was never intended to function as public API.

These projects reversed the current Send implementation.

Good examples might be Send itself and [`ffsend-api`](https://github.com/timvisee/ffsend-api) (from [`ffsend`](https://github.com/timvisee/ffsend)).
